build_from:
  aarch64: 'ghcr.io/home-assistant/aarch64-base:3.15'
  amd64: 'ghcr.io/home-assistant/amd64-base:3.15'
  armhf: 'ghcr.io/home-assistant/armhf-base:3.15'
  armv7: 'ghcr.io/home-assistant/armv7-base:3.15'
  i386: 'ghcr.io/home-assistant/i386-base:3.15'
labels:
  org.opencontainers.image.title: 'Home Assistant Add-on: APC UPS Daemon'
  org.opencontainers.image.description: Permits orderly shutdown of Home Assistant in the event of a power failure
  org.opencontainers.image.source: 'https://github.com/sstallion/homeassistant-addons/tree/main/apcupsd'
  org.opencontainers.image.licenses: BSD-2-Clause
